spring:
  application:
    name: lingoland-batch

  datasource:
    url: jdbc:postgresql://localhost:5432/lingoland
    username: postgres
    password: ssafy
    driver-class-name: org.postgresql.Driver

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/lingoland
    username: postgres
    password: ssafy
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30s

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

      reactor.core.publisher: DEBUG
      io.r2dbc.postgresql: DEBUG
      org.springframework.data.r2dbc: DEBUG

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  batch:
    jdbc:
      initialize-schema: always

  chatGPTKey: ${CHAT_GPT_KEY}
  executionCnt: 1