spring:
  application:
    name: lingoland-batch

  datasource:
    url: jdbc:postgresql://localhost:5432/lingoland
    username: postgres
    password: ssafy
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

      reactor.core.publisher: DEBUG
      io.r2dbc.postgresql: DEBUG
      org.springframework.data.r2dbc: DEBUG

  batch:
    jdbc:
      initialize-schema: never

  chatGPTKey: ${CHAT_GPT_KEY}
  executionCnt: 20
  taskletCnt: 1
server:
  port: 8081
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

